# site settings
title: FORCsensei
subtitle: by FORCaist
email: FORCaist.user@gmail.com
description: A package for processing and plotting of optimized First-order reversal curve (FORC) measurements
baseurl: "/FORCaist.github.io" # the subpath of your site, e.g. /blog
url: ""# the base hostname & protocol for your site
author:
street_address: Research Institute of Geology and Geoinformation, Geological Survey of Japan, National Institute of Advanced Industrial Science and Technology (AIST)
city: Tsukuba
state: Ibaraki
zip_code: 305-8567
country: Japan
phone: 1-800-FORC

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/FORCaist/forcsensei
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/forcaist

# build settings
markdown: kramdown

sass:
  style: compressed
